name: tombryant
favicon: null
layout_spectrum: 0.8968264881987125
typography_spectrum: 0.9554863676894456
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors: []
  brandStrength: 0.8464720314368606
  lightness: 0.7120206626132131
  saturation: 0.30845118477009237
  rhythmicContrast: 0.9545048594009131
purpose: []
